---

- name: "Download miniflux binary"
  ansible.builtin.get_url:
    url: "{{ miniflux_download_url_armv7 }}"
    dest: "/usr/local/bin/miniflux"
    mode: "0755"
    owner: "root"
    group: "root"
