---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:20.04}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - miniflux_group
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default
  test_sequence:
    - dependency
    # - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
verifier:
  name: ansible
